### PR TITLE
Added Identifier for Profile Image Upload

### PR DESCRIPTION
**Pull request by asingh0725**
Issue: #74, #60, #70, #68

### CODE REVIEW

**Review by jm278 — CHANGES_REQUESTED** [review]
When I add a comment my profile picture does not render the way it should be. 
Screenshot 2023-08-12 at 11 36 05 AM

**Review by Mustafabd — CHANGES_REQUESTED** [review]
I can see the upload image prompt when I hover over the Profile Icon, but when I make a comment, my Profile picture stays the same as the default profile picture even after I changed the profile image. Please fix this issue 
image

**Review by Mustafabd — APPROVED** [review]
It works very well! Good job

**Review by jm278 — APPROVED** [review]
Good job! I was able to edit my comments and delete them.

**Pull request merged**
