### PR TITLE
Created PostPage and Added Comments section

### PR DESCRIPTION
**Pull request by asingh0725**
Issue: #57 
- Upon clicking the post on the feed, users can access post page.
- Users can comment on the posts.
- the new features are responsive

### CODE REVIEW

**Review by jm278 — CHANGES_REQUESTED** [review]
- There should be an indicator that users can comment. Perhaps adding a "click to comment" would do the job. 
- When I clicked on the second post the website broke 
Screenshot 2023-08-11 at 12 37 16 PM

**Comment by asingh0725** [comment]
> * There should be an indicator that users can comment. Perhaps adding a "click to comment" would do the job.
> * When I clicked on the second post the website broke
> 
> Screenshot 2023-08-11 at 12 37 16 PM

Thank you for the comments! I addressed the changes in the latest commit

**Review by jm278 — APPROVED** [review]
Looks good!

**Review by Mustafabd — APPROVED** [review]
Works as planned.

**Pull request merged**
